default: raut_abhishek_pa3_lcs

raut_abhishek_pa3_lcs.o: raut_abhishek_pa3_lcs.c 
	gcc -c raut_abhishek_pa3_lcs.c -o raut_abhishek_pa3_lcs.o

raut_abhishek_pa3_lcs: raut_abhishek_pa3_lcs.o
	gcc raut_abhishek_pa3_lcs.o -o raut_abhishek_pa3_lcs

clean:
	-rm -f *.o
    
